"""Generate Chapter 5 result tables and learning-curve figures from the
consolidated ablation CSVs under thesis/data/.

This is a companion to generate_results_tables.py. The older script reads a
results/<scenario>/<obs>/<reward>/aggregate.csv layout; the ablation campaign
instead archives one summary.csv per study under thesis/data/phase*/. This
script reads those confirmed CSVs and writes exactly the tables and figures
Chapter 5 inputs, so the chapter always reflects the archived numbers.

Only confirmed (CSV-backed) results are emitted here. Results that live only in
development logs (the causal ladder, the obstacle drivability calibration) are
kept in hand-authored table stubs with '---' cells so the chapter compiles while
those numbers are imported.

Usage:
    python scripts/generate_phase_tables.py            # tables + figures
    python scripts/generate_phase_tables.py --no-figures
"""

from __future__ import annotations

import argparse
import csv
import math
import re
import statistics
from pathlib import Path

RAD2DEG = 180.0 / math.pi

THESIS_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = THESIS_DIR / "data"
P3_DIR = DATA_DIR / "phase3_hidden_path"
TABLES_DIR = THESIS_DIR / "tables"
FIGURES_DIR = THESIS_DIR / "figures" / "experiment_results"

AUTO_HEADER = "% Auto-generated by thesis/scripts/generate_phase_tables.py\n"

# Human-readable labels ------------------------------------------------------
ALGO_LABEL = {
    "td3": "TD3",
    "ppo": "PPO",
    "dqn": "DQN",
    "ppo_disc": "PPO (discrete)",
}
ALGO_ORDER = ["td3", "ppo", "dqn", "ppo_disc"]

REWARD_LABEL = {
    "dense": "Dense",
    "tractor_focus": "Tractor-focus",
    "multiplicative": "Multiplicative",
    "guided": "Guided (PP)",
    "no_hitch": "No-hitch",
}
FORWARD_REWARDS = ["dense", "tractor_focus", "multiplicative", "guided"]
REVERSE_REWARDS = ["dense", "no_hitch", "multiplicative", "guided"]

OBS_LABEL = {
    "state": "State (8)",
    "lidar8": "LiDAR-8 (10)",
    "lidar24": "LiDAR-24 (26)",
    "lidar64": "LiDAR-64 (66)",
    "bev": "BEV ($32{\\times}32$)",
}
OBS_ORDER = ["state", "lidar8", "lidar24", "lidar64", "bev"]

# Recoverability components mapped to thesis notation.
COMPONENT_SYMBOL = {
    "e_psi": "$e_\\psi$",
    "e_y": "$e_y$",
    "k1": "$\\kappa_1$",
    "k2": "$\\kappa_2$",
    "gamma_hitch": "$\\gamma$",
    "e_psi_t": "$e_{\\psi,t}$",
    "e_y_t": "$e_{y,t}$",
    "delta_steer": "$\\delta$",
}

# Clean descriptions, authored here rather than taken from the CSV note so the
# punctuation matches the thesis style (no semicolons or colons).
COMPONENT_DESC = {
    "e_psi": "tractor heading error, exteroceptive",
    "e_y": "tractor cross-track error, exteroceptive",
    "k1": "near curvature sample, exteroceptive",
    "k2": "far curvature sample, exteroceptive",
    "gamma_hitch": "hitch angle, partly visible through the path history",
    "e_psi_t": "trailer heading error, exteroceptive",
    "e_y_t": "trailer cross-track error, exteroceptive",
    "delta_steer": "steering angle, an internal actuator state the image cannot see",
}


def read_rows(path: Path) -> list[dict[str, str]]:
    """Read a CSV, skipping any leading or interleaved '#' comment lines."""
    with path.open(newline="") as f:
        rows = [ln for ln in f if not ln.lstrip().startswith("#")]
    return list(csv.DictReader(rows))


def key(row: dict[str, str], *fields: str) -> tuple[str, ...]:
    return tuple(row[f] for f in fields)


def fnum(value: str | None) -> float | None:
    if value is None or value == "" or value == "nan":
        return None
    try:
        return float(value)
    except ValueError:
        return None


def pct(mean: float | None, ci: float | None, decimals: int = 1, bold: bool = False) -> str:
    """Completion rendered as a percentage with a small +/- CI, or --- if absent."""
    if mean is None:
        return "---"
    m = mean * 100.0
    body = f"{m:.{decimals}f}"
    if ci is not None:
        body += f"{{\\scriptsize$\\pm${ci * 100.0:.{decimals}f}}}"
    return f"\\textbf{{{body}}}" if bold else body


def num(value: float | None, decimals: int = 3) -> str:
    return "---" if value is None else f"{value:.{decimals}f}"


def deg(value: float | None, decimals: int = 1) -> str:
    return "---" if value is None else f"{value * RAD2DEG:.{decimals}f}"


def write(path: Path, body: str) -> None:
    path.write_text(AUTO_HEADER + "\n" + body)
    print(f"wrote {path.relative_to(THESIS_DIR)}")


# --- Phase-1 algorithm x reward completion matrices -------------------------

def algo_reward_matrix(rows, direction, rewards, champion=None):
    idx = {key(r, "algo", "reward"): r for r in rows if r["direction"] == direction}
    header_cols = " & ".join(f"\\makecell{{{REWARD_LABEL[r]}}}" for r in rewards)
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        f"\\caption{{{direction.capitalize()} lane-following, best-checkpoint completion "
        "rate (\\%) for every algorithm and reward combination on the engineered state "
        "observation. Cells are the mean over three seeds with a 95\\% confidence "
        "interval. The chosen recipe is highlighted.}",
        f"\\label{{tab:algorithm_comparison_{direction}}}",
        "\\resizebox{\\ifdim\\width>\\linewidth \\linewidth\\else \\width\\fi}{!}{%",
        "\\begin{tabular}{l" + "c" * len(rewards) + "}",
        "\\toprule",
        f"Algorithm & {header_cols} \\\\",
        "\\midrule",
    ]
    for algo in ALGO_ORDER:
        cells = []
        for reward in rewards:
            r = idx.get((algo, reward))
            if r is None:
                cells.append("---")
                continue
            is_champ = champion == (algo, reward, direction)
            cells.append(pct(fnum(r["completion_mean"]), fnum(r["completion_ci95"]), bold=is_champ))
        lines.append(f"{ALGO_LABEL[algo]} & " + " & ".join(cells) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}%", "}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def td3_reverse_reward_detail(rows):
    idx = {r["reward"]: r for r in rows if r["algo"] == "td3" and r["direction"] == "reverse"}
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Reverse lane-following, TD3 reward detail on the engineered state "
        "observation. Beyond completion the multiplicative reward also gives the lowest "
        "trailer cross-track error and the tightest hitch behavior, which is why it is "
        "carried forward. Mean over three seeds, 95\\% confidence interval on completion.}",
        "\\label{tab:reward_ablation_reverse}",
        "\\resizebox{\\ifdim\\width>\\linewidth \\linewidth\\else \\width\\fi}{!}{%",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "Reward & \\makecell{Completion\\\\(\\%)} & \\makecell{Trailer CTE\\\\(m)} "
        "& \\makecell{Max $|\\gamma|$\\\\($^\\circ$)} & \\makecell{Jackknife\\\\(\\%)} \\\\",
        "\\midrule",
    ]
    for reward in REVERSE_REWARDS:
        r = idx.get(reward)
        if r is None:
            lines.append(f"{REWARD_LABEL[reward]} & --- & --- & --- & --- \\\\")
            continue
        bold = reward == "multiplicative"
        lines.append(
            f"{REWARD_LABEL[reward]} & "
            f"{pct(fnum(r['completion_mean']), fnum(r['completion_ci95']), bold=bold)} & "
            f"{num(fnum(r['trailer_cte_mean']), 2)} & "
            f"{deg(fnum(r['max_hitch_mean']))} & "
            f"{fnum(r['jackknife_mean']) * 100.0:.1f} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}%", "}", "\\end{table}"]
    return "\n".join(lines) + "\n"


# --- Classical baselines on the safe pool -----------------------------------

def parse_classical_log(path: Path):
    """Parse the simple '[forward]/[reverse]' safe-pool baseline log."""
    result = {"forward": {}, "reverse": {}}
    section = None
    for line in path.read_text().splitlines():
        s = line.strip()
        if s == "[forward]":
            section = "forward"
        elif s == "[reverse]":
            section = "reverse"
        elif section and "compl=" in s:
            name = s.split()[0]
            parts = {kv.split("=")[0]: float(kv.split("=")[1]) for kv in s.split() if "=" in kv}
            result[section][name] = parts
    return result


def classical_baselines_table(data):
    order = ["PurePursuit", "PID", "LQR", "MPC"]
    label = {"PurePursuit": "Pure pursuit", "PID": "PID", "LQR": "LQR", "MPC": "MPC"}
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Tuned classical controllers on the pure-pursuit-validated safe pool, "
        "the same evaluation pool used for the learned agents. Forward tracking is "
        "saturated for every controller; reverse separates them. These rates are the "
        "yardstick for the learned policy.}",
        "\\label{tab:classical_baselines}",
        "\\resizebox{\\ifdim\\width>\\linewidth \\linewidth\\else \\width\\fi}{!}{%",
        "\\begin{tabular}{lccccc}",
        "\\toprule",
        "Controller & \\makecell{Forward\\\\completion\\\\(\\%)} & \\makecell{Forward\\\\CTE (m)} "
        "& \\makecell{Reverse\\\\completion\\\\(\\%)} & \\makecell{Reverse\\\\CTE (m)} "
        "& \\makecell{Reverse\\\\Max $|\\gamma|$ ($^\\circ$)} \\\\",
        "\\midrule",
    ]
    for name in order:
        f = data["forward"].get(name, {})
        r = data["reverse"].get(name, {})
        lines.append(
            f"{label[name]} & "
            f"{f.get('compl', 0) * 100:.1f} & {num(f.get('cte'), 3)} & "
            f"{r.get('compl', 0) * 100:.1f} & {num(r.get('cte'), 3)} & "
            f"{deg(r.get('hitch'))} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}%", "}", "\\end{table}"]
    return "\n".join(lines) + "\n"


# --- Controller benchmark (TD3 champion vs classical) -----------------------

def benchmark_table(p1_rows, classical):
    td3 = {r["direction"]: r for r in p1_rows
           if r["algo"] == "td3" and r["obs"] == "state" and r["reward"] == "multiplicative"}
    order = ["TD3", "PurePursuit", "PID", "LQR", "MPC"]
    label = {"TD3": "TD3 (state, multiplicative)", "PurePursuit": "Pure pursuit",
             "PID": "PID", "LQR": "LQR", "MPC": "MPC"}

    def block(direction, caption, lbl):
        lines = [
            "\\begin{table}[H]",
            "\\centering",
            f"\\caption{{{caption}}}",
            f"\\label{{{lbl}}}",
            "\\resizebox{\\ifdim\\width>\\linewidth \\linewidth\\else \\width\\fi}{!}{%",
            "\\begin{tabular}{lccc}",
            "\\toprule",
            "Controller & \\makecell{Completion\\\\(\\%)} & \\makecell{Trailer CTE\\\\(m)} "
            "& \\makecell{Max $|\\gamma|$\\\\($^\\circ$)} \\\\",
            "\\midrule",
        ]
        for name in order:
            if name == "TD3":
                r = td3.get(direction)
                if r is None:
                    lines.append("TD3 (state, multiplicative) & --- & --- & --- \\\\")
                    continue
                lines.append(
                    f"{label[name]} & {pct(fnum(r['completion_mean']), fnum(r['completion_ci95']))} & "
                    f"{num(fnum(r['trailer_cte_mean']), 3)} & {deg(fnum(r['max_hitch_mean']))} \\\\"
                )
            else:
                c = classical[direction].get(name, {})
                lines.append(
                    f"{label[name]} & {c.get('compl', 0) * 100:.1f} & "
                    f"{num(c.get('cte'), 3)} & {deg(c.get('hitch'))} \\\\"
                )
        lines += ["\\bottomrule", "\\end{tabular}%", "}", "\\end{table}"]
        return "\n".join(lines)

    fwd = block("forward",
                "Forward lane-following controller benchmark on the safe pool. Tracking is "
                "saturated for every method, so completion cannot separate them here.",
                "tab:benchmark_forward")
    rev = block("reverse",
                "Reverse lane-following controller benchmark on the safe pool. The learned "
                "policy matches pure pursuit on completion and clears PID, while MPC, which "
                "receives an explicit path preview, is the informed upper bound.",
                "tab:benchmark_reverse")
    return fwd + "\n" + rev + "\n"


# --- Phase-2A observation ablation ------------------------------------------

def obs_ablation_table(rows):
    fwd = {r["obs"]: r for r in rows if r["direction"] == "forward"}
    rev = {r["obs"]: r for r in rows if r["direction"] == "reverse"}
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Observation-space ablation on no-obstacle lane-following, identical "
        "TD3 recipe (multiplicative reward, fixed speed) for every observation. "
        "Best-checkpoint completion and trailer cross-track error, mean over three seeds "
        "with a 95\\% confidence interval on completion. Reliability falls as the "
        "observation grows, and the effect is sharper in reverse. The reverse BEV run is "
        "deferred to the vision-rescue study.}",
        "\\label{tab:obs_ablation}",
        "\\resizebox{\\ifdim\\width>\\linewidth \\linewidth\\else \\width\\fi}{!}{%",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "Observation (dim) & \\makecell{Forward\\\\completion (\\%)} & \\makecell{Forward\\\\CTE (m)} "
        "& \\makecell{Reverse\\\\completion (\\%)} & \\makecell{Reverse\\\\CTE (m)} \\\\",
        "\\midrule",
    ]
    for obs in OBS_ORDER:
        f = fwd.get(obs)
        r = rev.get(obs)
        fc = pct(fnum(f["completion_mean"]), fnum(f["completion_ci95"])) if f else "---"
        fcte = num(fnum(f["trailer_cte_mean"]), 2) if f else "---"
        rc = pct(fnum(r["completion_mean"]), fnum(r["completion_ci95"])) if r else "---"
        rcte = num(fnum(r["trailer_cte_mean"]), 2) if r else "---"
        lines.append(f"{OBS_LABEL[obs]} & {fc} & {fcte} & {rc} & {rcte} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}%", "}", "\\end{table}"]
    return "\n".join(lines) + "\n"


# --- Phase-2B geometry recoverability ---------------------------------------

def recoverability_table(rows):
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Per-component test $R^2$ of predicting each state variable from the "
        "bird's-eye-view image alone, using the frozen geometry encoder. The exteroceptive "
        "path geometry is recovered almost perfectly, while the internal steering angle "
        "resists, which is why steering and the hitch angle are supplied as true "
        "proprioception rather than predicted.}",
        "\\label{tab:geometry_recoverability}",
        "\\begin{tabular}{lp{7.5cm}c}",
        "\\toprule",
        "Component & Description & $R^2$ \\\\",
        "\\midrule",
    ]
    for r in rows:
        symbol = COMPONENT_SYMBOL.get(r["component"], r["component"].replace("_", "\\_"))
        desc = COMPONENT_DESC.get(r["component"], r["note"])
        lines.append(f"{symbol} & {desc} & {fnum(r['R2']):.3f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


# --- Figures ----------------------------------------------------------------

def _plot_curves(curve_rows, direction, group_field, group_values, group_labels,
                 fixed, out_name, title):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    # Aggregate completion across seeds per (group, timestep).
    from collections import defaultdict
    series = {g: defaultdict(list) for g in group_values}
    for r in curve_rows:
        if r["direction"] != direction:
            continue
        if any(r[k] != v for k, v in fixed.items()):
            continue
        g = r[group_field]
        if g not in series:
            continue
        t = int(float(r["timesteps"]))
        c = fnum(r["completion"])
        if c is not None:
            series[g][t].append(c)

    fig, ax = plt.subplots(figsize=(6.0, 3.8))
    plotted = False
    for g in group_values:
        pts = sorted(series[g].items())
        if not pts:
            continue
        xs = [t / 1000.0 for t, _ in pts]
        ys = [sum(v) / len(v) * 100.0 for _, v in pts]
        ax.plot(xs, ys, marker="o", markersize=3, linewidth=1.6, label=group_labels[g])
        plotted = True
    if not plotted:
        plt.close(fig)
        return
    ax.set_xlabel("Training steps (thousands)")
    ax.set_ylabel("Completion (\\%)" if False else "Completion (%)")
    ax.set_title(title)
    ax.set_ylim(-3, 103)
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    out = FIGURES_DIR / out_name
    fig.savefig(out)
    plt.close(fig)
    print(f"wrote {out.relative_to(THESIS_DIR)}")


def figure_geometry_curve(rows):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    xs = [int(float(r["timesteps"])) / 1000.0 for r in rows]
    ys = [fnum(r["completion"]) * 100.0 for r in rows]
    fig, ax = plt.subplots(figsize=(6.0, 3.8))
    ax.plot(xs, ys, marker="o", markersize=4, linewidth=1.8, color="#1f77b4")
    ax.set_xlabel("Training steps (thousands)")
    ax.set_ylabel("Completion (%)")
    ax.set_title("Geometry-encoder policy, forward lane-following (seed 0)")
    ax.set_ylim(-3, 103)
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    out = FIGURES_DIR / "geometry_rl_curve.pdf"
    fig.savefig(out)
    plt.close(fig)
    print(f"wrote {out.relative_to(THESIS_DIR)}")


def build_figures():
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    obs_curves = read_rows(DATA_DIR / "phase2_obs_ablation_2A" / "curves.csv")
    obs_groups = OBS_ORDER
    obs_labels = {o: OBS_LABEL[o].split(" (")[0] for o in OBS_ORDER}
    for d in ("forward", "reverse"):
        _plot_curves(obs_curves, d, "obs", obs_groups, obs_labels,
                     {"algo": "td3", "reward": "multiplicative"},
                     f"{d}_obs_ablation.pdf",
                     f"Observation ablation, {d} lane-following")

    p1_curves = read_rows(DATA_DIR / "phase1_ablation_V1" / "curves.csv")
    for d, rewards in (("forward", FORWARD_REWARDS), ("reverse", REVERSE_REWARDS)):
        _plot_curves(p1_curves, d, "reward", rewards,
                     {r: REWARD_LABEL[r] for r in rewards},
                     {"algo": "td3", "obs": "state"},
                     f"{d}_reward_ablation.pdf",
                     f"Reward ablation (TD3), {d} lane-following")

    geom = read_rows(DATA_DIR / "phase2b_geometry_encoder" / "geom_rl_seed0_curve.csv")
    figure_geometry_curve(geom)


# === Phase 3: obstacle-aware maneuvering ====================================

def parse_multiseed_analysis(path):
    """Parse final_multiseed_analysis.txt into {model_name: {...}}."""
    models = {}
    cur = None
    for line in path.read_text().splitlines():
        m = re.match(r"### MODEL (\S+)\s+\(dir=(\w+) mild=(\w+) dynamic_diff=(\w+)\)", line)
        if m:
            cur = {"name": m.group(1), "dir": m.group(2), "dynamic": m.group(4) == "True",
                   "overall": {}, "buckets": []}
            models[m.group(1)] = cur
            continue
        if cur is None:
            continue
        mo = re.match(r"OVERALL n=(\d+)\s+complete=([\d.]+)\s+stop=([\d.]+)\s+crash=([\d.]+)", line)
        if mo:
            cur["overall"] = {"n": int(mo.group(1)), "complete": float(mo.group(2)),
                              "stop": float(mo.group(3)), "crash": float(mo.group(4))}
            continue
        mb = re.match(r"\s*\[([\d.]+),([\d.]+)\)\s+(\d+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+|nan)", line)
        if mb:
            cur["buckets"].append({"lo": float(mb.group(1)), "hi": float(mb.group(2)),
                                   "n": int(mb.group(3)), "complete": float(mb.group(4)),
                                   "stop": float(mb.group(5)), "crash": float(mb.group(6)),
                                   "hitch": mb.group(7)})
            continue
        mc = re.match(r"collision geometry: tractor-clip=([\d.]+) trailer-clip=([\d.]+)", line)
        if mc:
            cur["tractor_clip"] = float(mc.group(1))
            cur["trailer_clip"] = float(mc.group(2))
    return models


def parse_vision(path):
    """Parse final_multiseed_vision.txt -> {reverse:{r2,safe,crash}, forward:{...}}."""
    out = {"reverse": {"r2": {}}, "forward": {"r2": {}}}
    section = None
    for line in path.read_text().splitlines():
        if "REVERSE encoder" in line:
            section = "reverse"
        elif "FORWARD encoder" in line:
            section = "forward"
        if section is None:
            continue
        m = re.match(r"\s+(\w+)\s+R2=\+?([\d.\-]+)", line)
        if m:
            out[section]["r2"][m.group(1)] = float(m.group(2))
        ms = re.search(r"SAFE.*=\s*([\d.]+)\s+crash\s*=\s*([\d.]+)", line)
        if ms:
            out[section]["safe"] = float(ms.group(1))
            out[section]["crash"] = float(ms.group(2))
    return out


def obstacle_reverse_stratified_table(models):
    dyn = models["hp_reverse_avoidance_d_win_dyn_final_s0"]
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Reverse obstacle maneuvering, accepted dynamic-difficulty model, outcomes "
        "stratified by the maximum dynamic difficulty reached. Completion falls and stopping "
        "rises with difficulty, and no crash occurs below the gate at roughly 0.5. The "
        "low-difficulty stops are the accepted articulation limitation, not spurious behavior. "
        "Rates are provisional pending the fair-pool re-evaluation.}",
        "\\label{tab:obstacle_reverse_stratified}",
        "\\resizebox{\\ifdim\\width>\\linewidth \\linewidth\\else \\width\\fi}{!}{%",
        "\\begin{tabular}{lrcccc}",
        "\\toprule",
        "Dynamic difficulty & $n$ & \\makecell{Complete\\\\(\\%)} & \\makecell{Stop\\\\(\\%)} "
        "& \\makecell{Crash\\\\(\\%)} & \\makecell{Stop $|\\gamma|$\\\\(rad)} \\\\",
        "\\midrule",
    ]
    for b in dyn["buckets"]:
        hitch = "---" if b["hitch"] == "nan" else b["hitch"]
        lines.append(
            f"$[{b['lo']:.1f},{b['hi']:.1f})$ & {b['n']} & {b['complete']*100:.1f} & "
            f"{b['stop']*100:.1f} & {b['crash']*100:.1f} & {hitch} \\\\"
        )
    lines += ["\\bottomrule", "\\end{tabular}%", "}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def obstacle_multiseed_table(models):
    rev = [models[f"hp_reverse_avoidance_d_win_dyn_final_s{i}"] for i in range(3)]
    rev_crash = [m["overall"]["crash"] for m in rev]
    mean_c = statistics.mean(rev_crash)
    sd_c = statistics.stdev(rev_crash)
    fwd_dyn = [models[f"hp_forward_avoidance_d_win_dyn_final_s{i}"]["overall"]["crash"] for i in range(3)]
    fwd_static = models["hp_forward_avoidance_d_win_sharp_s0"]["overall"]["crash"]

    a = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Reverse dynamic-difficulty model across three seeds trained from scratch. "
        "Two of three seeds reproduce the safe result, and seed 1 converged to a less "
        "conservative policy. Rates are provisional pending the fair-pool re-evaluation.}",
        "\\label{tab:obstacle_multiseed}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Seed & \\makecell{Complete\\\\(\\%)} & \\makecell{Stop\\\\(\\%)} & \\makecell{Crash\\\\(\\%)} \\\\",
        "\\midrule",
    ]
    for i, m in enumerate(rev):
        o = m["overall"]
        a.append(f"Seed {i} & {o['complete']*100:.1f} & {o['stop']*100:.1f} & {o['crash']*100:.1f} \\\\")
    a.append(f"\\midrule\nMean $\\pm$ sd & & & {mean_c*100:.1f}{{\\scriptsize$\\pm${sd_c*100:.1f}}} \\\\")
    a += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]

    b = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Forward crash rate, static against dynamic difficulty. Dynamic difficulty "
        "hurts forward, so forward keeps the static recipe. Rates are provisional pending the "
        "fair-pool re-evaluation.}",
        "\\label{tab:obstacle_forward_recipe}",
        "\\begin{tabular}{lc}",
        "\\toprule",
        "Forward recipe & Crash (\\%) \\\\",
        "\\midrule",
        f"Static difficulty & {fwd_static*100:.1f} \\\\",
        f"Dynamic difficulty (mean of 3 seeds) & {statistics.mean(fwd_dyn)*100:.1f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(a) + "\n" + "\n".join(b) + "\n"


def obstacle_recoverability_table(fwd_rows, vision):
    fwd = {r["dim"]: fnum(r["test_R2"]) for r in fwd_rows}
    rev = vision["reverse"]["r2"]
    order = ["e_y", "e_psi", "e_y_t", "e_psi_t", "k1", "k2", "d_win"]
    label = {"e_y": "$e_y$", "e_psi": "$e_\\psi$", "e_y_t": "$e_{y,t}$", "e_psi_t": "$e_{\\psi,t}$",
             "k1": "$\\kappa_1$", "k2": "$\\kappa_2$", "d_win": "$d_{\\mathrm{win}}$"}
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Recoverability of the avoidance-path state from the obstacle image, test "
        "$R^2$ per component for the forward static and reverse dynamic recipes. The dynamic "
        "difficulty channel is highly recoverable in both directions, so there is no perception "
        "roadblock. Reverse avoidance-path curvature is softer than forward.}",
        "\\label{tab:obstacle_recoverability}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Component & Forward $R^2$ & Reverse $R^2$ \\\\",
        "\\midrule",
    ]
    for d in order:
        fv = f"{fwd[d]:.3f}" if d in fwd else "---"
        rv = f"{rev[d]:.3f}" if d in rev else "---"
        lines.append(f"{label[d]} & {fv} & {rv} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    return "\n".join(lines) + "\n"


def vision_closed_loop_table(vis_csv_rows, fwd_recov, vision):
    # forward: SAFE/crash from vision_closed_loop.csv, d_win R2 from encoder_recoverability.csv
    vp = next((r for r in vis_csv_rows if r["source"] == "vision_predicted_state"), None)
    fwd_dwin = next((fnum(r["test_R2"]) for r in fwd_recov if r["dim"] == "d_win"), None)
    rev = vision["reverse"]
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Closed-loop vision pipeline, policy driven on image-predicted avoidance-path "
        "state with a frozen encoder in the loop. The full pixels-to-control pipeline holds in "
        "both directions, a few points of crash above the ground-truth-state policy from "
        "prediction noise. Rates are provisional pending the fair-pool re-evaluation.}",
        "\\label{tab:vision_closed_loop}",
        "\\begin{tabular}{lccc}",
        "\\toprule",
        "Recipe & \\makecell{Difficulty\\\\$R^2$} & \\makecell{SAFE\\\\(\\%)} & \\makecell{Crash\\\\(\\%)} \\\\",
        "\\midrule",
        f"Forward (static) & {fwd_dwin:.3f} & {fnum(vp['safe'])*100:.1f} & {fnum(vp['crash'])*100:.1f} \\\\",
        f"Reverse (dynamic) & {rev['r2']['d_win']:.3f} & {rev['safe']*100:.1f} & {rev['crash']*100:.1f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def tail_swing_table(models):
    rev = [models[f"hp_reverse_avoidance_d_win_dyn_final_s{i}"] for i in range(3)]
    fwd = models["hp_forward_avoidance_d_win_sharp_s0"]
    rev_tractor = statistics.mean(m["tractor_clip"] for m in rev)
    rev_trailer = statistics.mean(m["trailer_clip"] for m in rev)
    lines = [
        "\\begin{table}[H]",
        "\\centering",
        "\\caption{Collision geometry by direction. Reverse crashes are dominated by trailer "
        "clips, which the body-extent difficulty window addresses, while forward crashes are "
        "entirely tractor clips, so the window fix is a reverse-only need.}",
        "\\label{tab:tail_swing}",
        "\\begin{tabular}{lcc}",
        "\\toprule",
        "Direction & \\makecell{Tractor clip\\\\(fraction)} & \\makecell{Trailer clip\\\\(fraction)} \\\\",
        "\\midrule",
        f"Forward & {fwd['tractor_clip']:.2f} & {fwd['trailer_clip']:.2f} \\\\",
        f"Reverse (mean of 3 seeds) & {rev_tractor:.2f} & {rev_trailer:.2f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def figure_reverse_crash_gate(models):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    dyn = models["hp_reverse_avoidance_d_win_dyn_final_s0"]
    xs = [(b["lo"] + b["hi"]) / 2 for b in dyn["buckets"]]
    crash = [b["crash"] * 100 for b in dyn["buckets"]]
    comp = [b["complete"] * 100 for b in dyn["buckets"]]
    stop = [b["stop"] * 100 for b in dyn["buckets"]]
    fig, ax = plt.subplots(figsize=(6.0, 3.8))
    ax.plot(xs, comp, marker="o", ms=3, lw=1.6, label="complete")
    ax.plot(xs, stop, marker="s", ms=3, lw=1.6, label="stop")
    ax.plot(xs, crash, marker="^", ms=3, lw=1.6, label="crash")
    ax.axvline(0.5, color="gray", ls="--", lw=1.0)
    ax.set_xlabel("Maximum dynamic difficulty")
    ax.set_ylabel("Outcome rate (%)")
    ax.set_title("Reverse obstacle maneuvering, outcome by dynamic difficulty")
    ax.set_ylim(-3, 103)
    ax.grid(True, alpha=0.3)
    ax.legend(fontsize=8)
    fig.tight_layout()
    out = FIGURES_DIR / "reverse_obstacle_gate.pdf"
    fig.savefig(out)
    plt.close(fig)
    print(f"wrote {out.relative_to(THESIS_DIR)}")


def build_phase3_tables():
    models = parse_multiseed_analysis(P3_DIR / "final_multiseed_analysis.txt")
    vision = parse_vision(P3_DIR / "final_multiseed_vision.txt")
    fwd_recov = read_rows(P3_DIR / "encoder_recoverability.csv")
    vis_csv = read_rows(P3_DIR / "vision_closed_loop.csv")

    write(TABLES_DIR / "obstacle_reverse_stratified.tex", obstacle_reverse_stratified_table(models))
    write(TABLES_DIR / "obstacle_multiseed.tex", obstacle_multiseed_table(models))
    write(TABLES_DIR / "obstacle_recoverability.tex", obstacle_recoverability_table(fwd_recov, vision))
    write(TABLES_DIR / "vision_closed_loop.tex", vision_closed_loop_table(vis_csv, fwd_recov, vision))
    write(TABLES_DIR / "tail_swing.tex", tail_swing_table(models))


def build_phase3_figures():
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    models = parse_multiseed_analysis(P3_DIR / "final_multiseed_analysis.txt")
    figure_reverse_crash_gate(models)


def build_tables():
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    p1 = read_rows(DATA_DIR / "phase1_ablation_V1" / "summary.csv")
    champion = ("td3", "multiplicative", "reverse")
    write(TABLES_DIR / "algorithm_comparison_forward.tex",
          algo_reward_matrix(p1, "forward", FORWARD_REWARDS, champion))
    write(TABLES_DIR / "algorithm_comparison_reverse.tex",
          algo_reward_matrix(p1, "reverse", REVERSE_REWARDS, champion))
    write(TABLES_DIR / "reward_ablation_reverse.tex", td3_reverse_reward_detail(p1))

    classical = parse_classical_log(DATA_DIR / "phase1_ablation_V1" / "classical_baselines_safepool.log")
    write(TABLES_DIR / "classical_baselines.tex", classical_baselines_table(classical))
    write(TABLES_DIR / "benchmark_results.tex", benchmark_table(p1, classical))

    p2a = read_rows(DATA_DIR / "phase2_obs_ablation_2A" / "summary.csv")
    write(TABLES_DIR / "obs_ablation_results.tex", obs_ablation_table(p2a))

    recov = read_rows(DATA_DIR / "phase2b_geometry_encoder" / "recoverability_forward.csv")
    write(TABLES_DIR / "geometry_recoverability.tex", recoverability_table(recov))

    build_phase3_tables()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-figures", action="store_true")
    args = ap.parse_args()
    build_tables()
    if not args.no_figures:
        build_figures()
        build_phase3_figures()


if __name__ == "__main__":
    main()
